### ISSUE TITLE
Cannot open Matrix-project in Visual Studio 2017

### ISSUE THREAD

**Issue by wlinna** [Half-Shot/matrix-dotnet-sdk#2]
When I open the solution in Visual Studio, Matrix.csproj doesn't show up, and Visual Studio doesn't complain.

Steps to reproduce

1. `git clone -b dotnet-core https://github.com/Half-Shot/matrix-dotnet-sdk.git matrix-dotnet-core-sdk`
2. Unload Tests-project
3. Try to see Matrix-project in Solution explorer

I ran `dotnet restore`, `dotnet build` and `dotnet test`, and they seem to finish successfully. But this still doesn't work on VS 2017.

If I load Tests-project, it just complains about Matrix-project:

`Unable to find project information for '<xxx>\matrix-dotnet-core-sdk\Matrix\Matrix.csproj'. The project file may be invalid or missing targets required for restore.	Tests	<xxx>\matrix-dotnet-core-sdk\Matrix\Tests\Tests.csproj`

I have installed .NET Core 2 SDK and .NET Core Cross-Platform tools for VS 2017. I'm using Windows 10. While I have .NET programming experience, this is my first time trying to use .NET Core.

(With that said, I couldn't compile master branch either)

**Comment by Half-Shot** [comment]
I don't think this is still the case, will get @turt2live to confirm it at some point :innocent:

**Comment by turt2live** [comment]
seems to load fine for me, but there are complaints:
![image](https://user-images.githubusercontent.com/1190097/52528050-fb078e80-2c90-11e9-97e0-7f0f013f09da.png)

**Comment by Half-Shot** [comment]
That can probably be filed under a new issue tbh. Looks like it loads.
